# Generated by Django 2.2.6 on 2019-12-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191218_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='flight',
        ),
    ]
